### ISSUE TITLE
Answer unanswered StackOverflow questions with high score

### ISSUE THREAD

**Issue by Benjamin-Loison** [Benjamin-Loison/YouTube-operational-API#108]
https://stackoverflow.com/search?page=2&tab=Votes&q=answers%3a0%20%5byoutube%5d%20or%20%5byoutube-analytics%5d%20or%20%5byoutube-analytics-api%5d%20or%20%5byoutube-api%5d%20or%20%5byoutube-channels%5d%20or%20%5byoutube-data-api%5d%20or%20%5byoutube-livestreaming-api%5d%20or%20%5byt%5d

- [ ] https://stackoverflow.com/q/50236607
- [ ] https://stackoverflow.com/q/28146259
- [ ] https://stackoverflow.com/q/57595484
- [ ] https://stackoverflow.com/q/48315310
- [ ] https://stackoverflow.com/q/26869672
- [ ] https://stackoverflow.com/q/30546686
- [ ] https://stackoverflow.com/q/51289599
